### ISSUE TITLE
`govendor add` pulls in unwanted tests for dependencies, in a broken way

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#24]
I'm using govendor at 9de80febcf158338d5eb650b395315d8d4a72a6e. It appears that the current behavior of `govendor add +e` is to import the test files from the packages on which I depend.

This may be annoying for some users, for the reasons discussed in golang/go#11659. But more importantly, `govendor add` does not pull in the transitive dependencies of the tests if they include packages that my code doesn't depend on.

For example, if my command depends on `golang.org/x/oauth2/google` and I use `govendor add +e` to vendor that package, the next time I run `go test ./...` I see the following:

    % go test ./...
    # github.com/googlecloudplatform/gcsfuse/vendor/golang.org/x/oauth2/google
    vendor/golang.org/x/oauth2/google/example_test.go:18:2: cannot find package "google.golang.org/appengine" in any of:
            /Users/jacobsa/go/src/github.com/googlecloudplatform/gcsfuse/vendor/google.golang.org/appengine (vendor tree)
            /Users/jacobsa/clients/go/src/google.golang.org/appengine (from $GOROOT)
            /Users/jacobsa/go/src/google.golang.org/appengine (from $GOPATH)
    FAIL    github.com/googlecloudplatform/gcsfuse/vendor/golang.org/x/oauth2/google [setup failed]

Note that I'm using `GO15VENDOREXPERIMENT=1`.

**Comment by kardianos** [comment]
Thanks. I'll look into it and see what's up.

**Comment by jacobsa** [comment]
If it helps, you can reproduce this at GoogleCloudPlatform/gcsfuse@a7c1465. (Be careful about using `git status` to see what has been added, because the `.gitignore` file in that repo ignores tests in order to help work around this shortcoming in `govendor` and `godep`.)

**Comment by kardianos** [comment]
@jacobsa I think the govendor behavior where it failed to pull in all dependencies is fixed. I've tested but I'd like you to confirm.

Per issue #14, I would like to add two options when vendoring:
Ignore tags []string

Common tag ignores might be "test" and "appengine".

I'm tentatively not adding to CLI, but rather adding to the vendor.json file. By default "govendor init" would include ignoreTags: ["test"], .

How does this sound to you?

**Comment by jacobsa** [comment]
I do like your tag-based solution configured with `vendor.json`.

But I think I still see the dependency problem. Here's how I can reproduce, first using godep to get `$GOPATH` into a working state based on the current dependencies of my project:

    go get -u github.com/tools/godep
    rm -rf $GOPATH/src
    mkdir -p $GOPATH/src/github.com/googlecloudplatform
    git clone https://github.com/GoogleCloudPlatform/gcsfuse.git $GOPATH/src/github.com/googlecloudplatform/gcsfuse
    
    cd $GOPATH/src/github.com/googlecloudplatform/gcsfuse
    git checkout b650d36
    godep restore
    
    git rm .gitignore
    git commit -m "stop ignoring tests to make it easier to debug"
    
    git rm -r Godeps/ vendor/
    git commit -m "unvendor"
    
    govendor init
    mkdir -p vendor
    govendor add +e
    git add vendor.json vendor/
    git commit -m "revendor with govendor"
    
    go test ./vendor/golang.org/...

The last command gives me:

```
vendor/golang.org/x/oauth2/google/example_test.go:18:2: cannot find package "google.golang.org/appengine" in any of:
        /Users/jacobsa/go/src/github.com/googlecloudplatform/gcsfuse/vendor/google.golang.org/appengine (vendor tree)
        /Users/jacobsa/clients/go/src/google.golang.org/appengine (from $GOROOT)
        /Users/jacobsa/go/src/google.golang.org/appengine (from $GOPATH)
FAIL    github.com/googlecloudplatform/gcsfuse/vendor/golang.org/x/oauth2/google [setup failed]
```

which says to me that the dependencies of `example_test.go` were not correctly pulled in. I could be misunderstanding, though.

For the record: I'm using govendor at b36aaa3777d87f88818d70d8a8a39a4b462cd9ab, with `GO15VENDOREXPERIMENT` set.

**Comment by kardianos** [comment]
@jacobsa Thank you for all the detailed repo cases. These are great!

I haven't tested this, but what I suspect is happening is that Godeps uses go build tags to determine dependencies so appengine isn't brought in.  Thus the test that relies on it fails. I'm guessing if you ran "govendor list +m" you would see appengine is missing. From first glance it looks like this would be solved by not vendoring test files (or removing them from the vendor tree). Confirm?

**Comment by jacobsa** [comment]
To be clear, I assume you're talking about [this](https://github.com/golang/oauth2/blob/8914e5017ca260f2a3a1575b1e6868874050d95e/google/example_test.go#L5) line from example_test.go?

    // +build appenginevm !appengine

As far as I can tell from [the documentation](http://golang.org/pkg/go/build/), this matches the boolean formula

    'appenginevm' present OR 'appengine' not present

Since I haven't told govendor anything about tags, `appengine` isn't present and so this file should be matched and its dependencies processed, right?

**Comment by kardianos** [comment]
@jacobsa I think you are correct, however at rev b36aaa3 it doesn't look like the vendor folder includes 
"vendor/google.golang.org/appengine". Thus your command sequence didn't move it over nor vendor it. As you are setting the entire root, it wasn't able to find it. But as you noted, tests will still match it due to the !appengine tag.

As such, I *think* it is working as intended.

**Comment by jacobsa** [comment]
@kardianos: I think you got the wrong revision number; that's a govendor revision. Note that my instructions _create_ the `vendor/` folder using govendor. It's govendor that's not pulling in the dependency—that's the bug I'm talking about.

In other words: I think govendor should be pulling in `google.golang.org/appengine` when I run `govendor add +e` since that command also pulls in `golang.org/x/oauth2/google/example_test.go`, but it does not do so.

**Comment by jacobsa** [comment]
Perhaps the use of godep and my large project are confusing the issue. [Here](https://gist.github.com/jacobsa/358306654373a7f0de33/0359231791b91df17f812de7e14885a028f00157) is a tiny gist that shows the problem. Reproduce as follows:

    # Download the code, then download its dependencies.
    git clone https://gist.github.com/358306654373a7f0de33.git $GOPATH/src/foo
    cd $GOPATH/src/foo
    go get -v -u -t ./...
    
    # Select a particular version.
    git checkout 0359231
    
    # Testing works now.
    go test ./...
    
    # After asking govendor to do its thing, testing fails.
    govendor init
    govendor add +e
    go test ./...

The error looks like before:

```
vendor/golang.org/x/oauth2/google/example_test.go:18:2: cannot find package "google.golang.org/appengine" in any of:
        /Users/jacobsa/go/src/foo/vendor/google.golang.org/appengine (vendor tree)
        /Users/jacobsa/clients/go/src/google.golang.org/appengine (from $GOROOT)
        /Users/jacobsa/go/src/google.golang.org/appengine (from $GOPATH)
```

Looking closer at `govendor list`, it seems that `google.golang.org/appengine` is listed with status `missing`. So govendor is aware that the dependency is needed, but when I say `govendor add +e` I've selected only the external ones that are not missing. If I instead manually install `google.golang.org/appengine`, everything works fine.

This is unfortunate, because I can't use `go get -u -t ./...` to ensure that everything I'll need is in `$GOPATH`; instead I need to do something ugly like:

    go get -u -t ./...
    go get $(govendor list +m | grep -o -P '(?<=^m )\S+$')
    govendor add +e

And even then, it could be that the missing packages themselves bring along yet _more_ new missing dependencies, so I need to run it over and over until nothing new is fetched.

Perhaps govendor should have a command that does this for me. Thoughts?

**Comment by jacobsa** [comment]
(By the way, I'll point out again that this problem goes away completely if you just don't pull in tests, at least for this case.)

**Comment by kardianos** [comment]
@jacobsa Yes, govendor will list it as missing and it goes away if we don't pull in tests.

There are open issues for not pulling in tests (soon to be addressed #9 #14). I just opened the issue #33 for fetching missing packages. Good points. Given those, let's close this issue.

**Comment by dghubble** [comment]
@jacobsa I think I've arrived here for the opposite reason, I noticed google.golang.org/appengine gets vendored as a dependency as a result of golang.org/x/oauth2/google/example_test.go when using +external. My initial expectation was that test deps wouldn't be vendored.

**Comment by jacobsa** [comment]
@dghubble: I'm totally happy for test deps to not be vendored, as long as _tests_ aren't vendored either. The problem here is that govendor goes halfway: it vendors the tests, but not in a way where they can be built.

**Comment by kardianos** [comment]
@jacobsa I'm fairly sure it would vendor test dependencies so long as they are in GOPATH. I'm sure you're busy, but if you don't think that is the case, could you modify "context/context_test.go" to provide a failing case? I am working on supporting build tags.

**Comment by jacobsa** [comment]
@kardianos: Sorry you're right, that was unfair. As I fleshed out in my [earlier comment](https://github.com/kardianos/govendor/issues/24#issuecomment-128243779), the issue is that it's difficult for the user to pull in everything they need into `$GOPATH`, since each invocation of `govendor add` may require new things to be in `$GOPATH`.

Anyway, ignoring tests obviates this particular issue for me, so thank you. For the record though: it would still be an issue if I wanted to pull in tests.
